from sqlalchemy.orm import Session
from models.database import FlashcardSet, Flashcard, FlashcardProgress, Document
from utils.llm_client import llm_client
from models.schema import FlashcardStudyRequest, FlashcardStudyResponse
from datetime import datetime, timedelta
import uuid
from typing import List, Dict, Any

class FlashcardService:
    async def generate_flashcards_from_document(self, document_id: int, num_cards: int, db: Session):
        """Fetch pre-generated flashcards from document (generated by Skill-Anything)"""
        
        # Get document
        document = db.query(Document).filter(Document.id == document_id).first()
        if not document:
            raise Exception("Document not found")
            
        # Get flashcard set
        flashcard_set = db.query(FlashcardSet).filter(FlashcardSet.document_id == document_id).order_by(FlashcardSet.created_at.desc()).first()
        if not flashcard_set:
            # Fallback to on-the-fly generation
            print("Flashcards not found in DB. Generating on the fly...")
            from utils.llm_client import llm_client
            generated_cards = await llm_client.generate_flashcards(document.text_content[:15000], num_cards)
            
            import uuid
            from datetime import datetime
            
            flashcard_set = FlashcardSet(
                id=str(uuid.uuid4()),
                document_id=document_id,
                user_id=document.user_id
            )
            db.add(flashcard_set)
            
            for card in generated_cards:
                card_id = str(uuid.uuid4())
                flashcard = Flashcard(
                    id=card_id,
                    set_id=flashcard_set.id,
                    question=card['question'],
                    answer=card['answer']
                )
                db.add(flashcard)
                
                # Auto-create progress
                progress = FlashcardProgress(
                    user_id=document.user_id,
                    flashcard_id=card_id,
                    next_review=datetime.utcnow()
                )
                db.add(progress)
            
            db.commit()
            
        flashcards_output = []
        
        # Use a join to get progress along with flashcards
        results = db.query(Flashcard, FlashcardProgress).join(
            FlashcardProgress, Flashcard.id == FlashcardProgress.flashcard_id
        ).filter(
            Flashcard.set_id == flashcard_set.id,
            FlashcardProgress.user_id == document.user_id
        ).all()
        
        for card, progress in results:
            flashcards_output.append({
                "id": card.id,
                "question": card.question,
                "answer": card.answer,
                "next_review": progress.next_review
            })
            
        # Optionally slice to num_cards
        if len(flashcards_output) > num_cards:
            import random
            flashcards_output = random.sample(flashcards_output, num_cards)
            
        return {
            "set_id": flashcard_set.id,
            "document_id": document_id,
            "flashcards": flashcards_output,
            "created_at": flashcard_set.created_at
        }
    
    def study_flashcard(self, study_request: FlashcardStudyRequest, db: Session, user_id: int) -> FlashcardStudyResponse:
        """Record flashcard study session with FSRS algorithm"""
        try:
            from fsrs import FSRS, Card, Rating, State
            has_fsrs = True
        except ImportError:
            has_fsrs = False
            import logging
            logging.error("FSRS package not installed. Using fallback SM-2.")
        
        # Get progress record
        progress = db.query(FlashcardProgress).filter(
            FlashcardProgress.user_id == user_id,
            FlashcardProgress.flashcard_id == study_request.flashcard_id
        ).first()
        
        if not progress:
            progress = FlashcardProgress(
                user_id=user_id,
                flashcard_id=study_request.flashcard_id,
                ease_factor=2.5,
                interval_days=0,
                review_count=0
            )
            db.add(progress)
            
        now = datetime.utcnow()
        
        if has_fsrs:
            f = FSRS()
            # Map frontend rating (1=Again, 2=Hard, 4=Good, 5=Easy) to FSRS Rating
            rating_map = {
                1: Rating.Again,
                2: Rating.Hard,
                3: Rating.Good,
                4: Rating.Good,
                5: Rating.Easy
            }
            fsrs_rating = rating_map.get(study_request.ease_rating, Rating.Good)
            
            # Reconstruct FSRS Card
            card = Card()
            card.state = State(progress.fsrs_state) if progress.fsrs_state is not None else State.New
            card.stability = progress.fsrs_stability or 0.0
            card.difficulty = progress.fsrs_difficulty or 0.0
            card.elapsed_days = progress.fsrs_elapsed_days or 0
            card.scheduled_days = progress.fsrs_scheduled_days or 0
            card.reps = progress.fsrs_reps or 0
            card.lapses = progress.fsrs_lapses or 0
            # Note: py-fsrs expects timezone-aware datetimes in newer versions, but utcnow is fine for generic use
            if progress.last_reviewed:
                card.last_review = progress.last_reviewed.replace(tzinfo=datetime.timezone.utc) if progress.last_reviewed.tzinfo is None else progress.last_reviewed
            
            # Calculate next review
            scheduling_cards = f.repeat(card, now.replace(tzinfo=datetime.timezone.utc))
            card = scheduling_cards[fsrs_rating].card
            
            # Update progress record
            progress.fsrs_state = card.state.value
            progress.fsrs_stability = card.stability
            progress.fsrs_difficulty = card.difficulty
            progress.fsrs_elapsed_days = card.elapsed_days
            progress.fsrs_scheduled_days = card.scheduled_days
            progress.fsrs_reps = card.reps
            progress.fsrs_lapses = card.lapses
            
            # Remove timezone for SQLite/Postgres naive columns
            progress.next_review = card.due.replace(tzinfo=None)
            progress.last_reviewed = now
            progress.interval_days = card.scheduled_days
            progress.review_count = card.reps
            
        else:
            # Fallback SM-2 Algorithm
            q = study_request.ease_rating
            if q >= 3:
                if progress.review_count == 0:
                    progress.interval_days = 1
                elif progress.review_count == 1:
                    progress.interval_days = 6
                else:
                    progress.interval_days = round(progress.interval_days * progress.ease_factor)
                progress.ease_factor = max(1.3, progress.ease_factor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02)))
                progress.review_count += 1
            else:
                progress.interval_days = 1
                progress.review_count = 0 
            progress.next_review = now + timedelta(days=progress.interval_days)
            progress.last_reviewed = now

        db.commit()
        
        return FlashcardStudyResponse(
            flashcard_id=study_request.flashcard_id,
            next_review_date=progress.next_review,
            interval_days=progress.interval_days
        )
    
    def get_cards_for_review(self, user_id: int, db: Session) -> List[Dict[str, Any]]:
        """Get flashcards due for review using efficient JOIN"""
        
        now = datetime.utcnow()
        
        # Optimized query using JOIN to get both progress and card content
        results = db.query(Flashcard, FlashcardProgress).join(
            FlashcardProgress, Flashcard.id == FlashcardProgress.flashcard_id
        ).filter(
            FlashcardProgress.user_id == user_id,
            FlashcardProgress.next_review <= now
        ).all()
        
        review_cards = []
        for card, progress in results:
            review_cards.append({
                "flashcard_id": card.id,
                "question": card.question,
                "answer": card.answer,
                "review_count": progress.review_count,
                "last_interval": progress.interval_days,
                "next_review": progress.next_review
            })
        
        return review_cards
